from enum import Enum


class ObjectType(str, Enum):
    """All inventory object types."""
    
    FOLDER = "FOLDER"
    WORKFLOW = "WORKFLOW"
    LOCK = "LOCK"
    NOTICEBOARD = "NOTICEBOARD"
    JOBRESOURCE = "JOBRESOURCE"
    FILEORDERSOURCE = "FILEORDERSOURCE"
    SCHEDULE = "SCHEDULE"
    WORKINGDAYSCALENDAR = "WORKINGDAYSCALENDAR"
    NONWORKINGDAYSCALENDAR = "NONWORKINGDAYSCALENDAR"
    JOBTEMPLATE = "JOBTEMPLATE"
    INCLUDESCRIPT = "INCLUDESCRIPT"
    REPORT = "REPORT"
    DEPLOYMENTDESCRIPTOR = "DEPLOYMENTDESCRIPTOR"
    DESCRIPTORFOLDER = "DESCRIPTORFOLDER"


class DeployObjectType(str, Enum):
    """Only deployable inventory object types."""
    
    FOLDER = "FOLDER"
    WORKFLOW = "WORKFLOW"
    LOCK = "LOCK"
    NOTICEBOARD = "NOTICEBOARD"
    JOBRESOURCE = "JOBRESOURCE"
    FILEORDERSOURCE = "FILEORDERSOURCE"


class ReleaseObjectType(str, Enum):
    """Only releasable inventory object types."""
    
    FOLDER = "FOLDER"
    SCHEDULE = "SCHEDULE"
    WORKINGDAYSCALENDAR = "WORKINGDAYSCALENDAR"
    NONWORKINGDAYSCALENDAR = "NONWORKINGDAYSCALENDAR"
    JOBTEMPLATE = "JOBTEMPLATE"
    INCLUDESCRIPT = "INCLUDESCRIPT"
    REPORT = "REPORT"


class DescriptorObjectType(str, Enum):
    DEPLOYMENTDESCRIPTOR = "DEPLOYMENTDESCRIPTOR"
    DESCRIPTORFOLDER = "DESCRIPTORFOLDER"